imports:
    - { resource: test_common.yaml }

parameters:
    integration_http_log_path: '%env(HTTP_LOG_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\ApplicationState:
        public: true

    App\Services\BackoffStrategyFactory:
        class: App\Tests\Services\Integration\BackoffStrategyFactory
        arguments:
            $maximumNumberOfDelays: '%callback_retry_limit%'

    App\Tests\Services\EntityRefresher:
        public: true

    App\Tests\Services\Integration\HttpLoggerFactory:

    app.tests.services.integration.httplogger:
        class: Psr\Log\LoggerInterface
        factory: [ '@App\Tests\Services\Integration\HttpLoggerFactory', 'create' ]
        arguments:
            $path: '%kernel.project_dir%/%integration_http_log_path%'

    App\Tests\Services\Integration\HttpLogReader:
        public: true
        arguments:
            $path: '%kernel.project_dir%/%integration_http_log_path%'

    webignition\HttpHistoryContainer\LoggableContainer:
        arguments:
            $logger: '@app.tests.services.integration.httplogger'

    App\Tests\Services\Guzzle\Middleware\Factory\HistoryMiddlewareFactory:

    GuzzleHttp\HandlerStack:
        factory: [ '@App\Tests\Services\Guzzle\HandlerStackFactory', 'create' ]
        arguments:
            $handler: '@app.tests.services.guzzle.handler.curl'
            $middlewareFactories:
                - '@App\Tests\Services\Guzzle\Middleware\Factory\HistoryMiddlewareFactory'