# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    compiler_source_directory: '%env(COMPILER_SOURCE_DIRECTORY)%'
    compiler_target_directory: '%env(COMPILER_TARGET_DIRECTORY)%'
    callback_retry_limit: '%env(CALLBACK_RETRY_LIMIT)%'
    job_timeout_check_period: '%env(JOB_TIMEOUT_CHECK_PERIOD)%'
    job_completed_check_period: '%env(JOB_COMPLETED_CHECK_PERIOD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    app.services.compiler-client:
        class: webignition\TcpCliProxyClient\Client
        factory: [ 'webignition\TcpCliProxyClient\Client', 'createFromHostAndPort' ]
        arguments:
            $host: '%env(COMPILER_HOST)%'
            $port: '%env(COMPILER_PORT)%'

    Symfony\Component\Yaml\Parser:
        class: Symfony\Component\Yaml\Parser

    App\Services\Compiler:
        arguments:
            $client: '@app.services.compiler-client'
            $compilerSourceDirectory: '%env(COMPILER_SOURCE_DIRECTORY)%'
            $compilerTargetDirectory: '%env(COMPILER_TARGET_DIRECTORY)%'

    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client

    webignition\TcpCliProxyClient\HandlerFactory:
        class: webignition\TcpCliProxyClient\HandlerFactory

    app.services.delegator-client:
        class: webignition\TcpCliProxyClient\Client
        factory: [ 'webignition\TcpCliProxyClient\Client', 'createFromHostAndPort' ]
        arguments:
            $host: '%env(DELEGATOR_HOST)%'
            $port: '%env(DELEGATOR_PORT)%'

    App\Services\TestExecutor:
        arguments:
            $delegatorClient: '@app.services.delegator-client'

    webignition\YamlDocumentGenerator\YamlGenerator:
        class: webignition\YamlDocumentGenerator\YamlGenerator

    Symfony\Component\Yaml\Dumper: ~

    App\Services\CallbackSender:
        arguments:
            $retryLimit: '%callback_retry_limit%'

    App\MessageDispatcher\TimeoutCheckMessageDispatcher:
        arguments:
            $recheckPeriodInSeconds: '%job_timeout_check_period%'

    App\MessageDispatcher\JobCompletedCheckMessageDispatcher:
        arguments:
            $recheckPeriodInSeconds: '%job_completed_check_period%'

    webignition\JsonMessageSerializerBundle\Services\MessageFactory:
        arguments:
            $typeToMessageClassMap:
                'job-ready': 'App\Message\JobReadyMessage'
                'compile-source': 'App\Message\CompileSourceMessage'
                'execute-test': 'App\Message\ExecuteTestMessage'
                'send-callback': 'App\Message\SendCallbackMessage'
                'timeout-check': 'App\Message\TimeoutCheckMessage'

    app.services.path-prefix-remover.compiler-source:
        class: webignition\StringPrefixRemover\DefinedStringPrefixRemover
        arguments:
            $prefix: '%compiler_source_directory%/'

    App\Services\SourcePathFinder:
        arguments:
            $compilerSourcePathPrefixRemover: '@app.services.path-prefix-remover.compiler-source'

    App\Services\TestDocumentMutator:
        arguments:
            $compilerSourcePathPrefixRemover: '@app.services.path-prefix-remover.compiler-source'

    webignition\BasilWorker\StateBundle\Services\SourcePathFinder:
        calls:
            - setCompilerSourcePathPrefixRemover: ['@app.services.path-prefix-remover.compiler-source']

    App\Services\CallbackFactory:
        arguments:
            $eventCallbackFactories:
                - '@App\Services\EventCallbackFactory\CompilationStartedEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\CompilationPassedEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\CompilationFailedEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\TestEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\JobTimeoutEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\NoPayloadEventCallbackFactory'
