imports:
    - { resource: services/test_common.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\TestConfigurationStore:
        public: true

    App\Services\TestStore:
        public: true

    App\Services\Compiler:
        public: true
        arguments:
            $client: '@app.services.compiler-client'
            $compilerSourceDirectory: '%env(COMPILER_SOURCE_DIRECTORY)%'
            $compilerTargetDirectory: '%env(COMPILER_TARGET_DIRECTORY)%'

    App\Services\CallbackSender:
        public: true
        arguments:
            $retryLimit: '%callback_retry_limit%'

    App\MessageHandler\CompileSourceHandler:
        public: true

    App\Services\SourcePathFinder:
        public: true
        arguments:
            $compilerSourcePathPrefixRemover: '@app.services.path-prefix-remover.compiler-source'

    App\Services\CompilationWorkflowHandler:
        public: true

    App\Services\TestExecutor:
        public: true
        arguments:
            $delegatorClient: '@app.services.delegator-client'

    App\MessageHandler\ExecuteTestHandler:
        public: true

    App\Services\ExecutionWorkflowHandler:
        public: true

    App\Services\TestFactory:
        public: true

    App\Services\CallbackResponseHandler:
        public: true

    App\Services\SourceCompileEventDispatcher:
        public: true

    App\MessageDispatcher\SendCallbackMessageDispatcher:
        public: true

    App\Services\TestCanceller:
        public: true

    App\Services\CallbackStore:
        public: true

    App\Services\CallbackStateMutator:
        public: true

    App\Repository\CallbackRepository:
        public: true

    App\Services\CallbackFactory:
        public: true

    App\Services\CallbackEventFactory:
        public: true

    App\Services\SourceCompileEventFactory:
        public: true

    App\Services\SourceFactory:
        public: true

    App\MessageHandler\TimeoutCheckHandler:
        public: true

    App\MessageDispatcher\TimeoutCheckMessageDispatcher:
        public: true
        arguments:
            $recheckPeriodInSeconds: '%job_timeout_check_period%'

    App\MessageHandler\JobReadyHandler:
        public: true

    App\Tests\Services\JobReadyEventSubscriber:
        public: true

    App\Tests\Services\CallbackHttpErrorEventSubscriber:
        public: true

    app.tests.services.guzzle.handler.queuing:
        public: true
        class: GuzzleHttp\Handler\MockHandler
        factory: [ '@App\Tests\Services\Guzzle\HandlerFactory', 'createQueuingMockHandler' ]

    GuzzleHttp\HandlerStack:
        factory: [ '@App\Tests\Services\Guzzle\HandlerStackFactory', 'create' ]
        arguments:
            $handler: '@app.tests.services.guzzle.handler.queuing'

    App\Tests\Services\TestTestFactory:
        public: true

    App\Tests\Services\TestTestRepository:
        public: true

    Symfony\Component\Messenger\Transport\InMemoryTransport:
        alias: 'messenger.transport.async'

    App\Tests\Services\TestCallbackEventFactory:
        public: true

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'
