name: Container Integration Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration-image:
    name: Integration tests (image)
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:password!@127.0.0.1:5432/basil-worker-db?charset=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: amqp, pgsql

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Setup integration environment
        run: composer image-integration-setup

      - name: Run asynchronous tests in image
        run: composer test-integration-image
